pull_request_rules:
  - name: automatic merge on CI success
    conditions:
      - status-success=Node.js CI
      - label=automerge
    actions:
      merge:
        method: rebase
        strict: true
  - name: remove automerge label on CI failure
    conditions:
      - status-failure=Node.js CI
      - label=automerge
    actions:
      label:
        remove:
          - automerge
  - name: remove outdated reviews
    conditions:
      - base=main
    actions:
      dismiss_reviews:
        changes_requested: true
