language: node_js
node_js:
  - "lts/*"
branches:
  only:
    - master

matrix:
  include:
  - name: Client
    env: PACKAGE_LOCATION=client
  - name: Server
    env: PACKAGE_LOCATION=server

before_install:
  - cd $PACKAGE_LOCATION

script:
  - npm run format
  - npm run lint
  - npm run build
  - npm run test
